server:
  port: 8081

spring:
  boot:
    admin:
      instance-auth:
        default-user-name: sihai
        default-password: root
      notify:
        mail:
          from: 1075991706@qq.com
          to: 13169186610@163.com
          ignore-changes:
  ## ??????
  mail:
    host: smtp.qq.com
    port: 465
    username: 1075991706@qq.com
    password: 
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
